language: java
sudo: false
install: mvn -T 2 -Ptravis -DskipTests=true -B -V install
script: mvn -T 2 -Ptravis ${JACOCO} test
matrix:
 include:
   # Covers Java 7, Open JDK, and code coverage
   - jdk: openjdk7
     env: JACOCO=-Pjacoco
   # Covers Java 8, Oracle JDK
   - jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
git:
  depth: 10
after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi